version: '{branch}-{build}'

skip_non_tags: true

environment:
  PATH: 'C:\Program Files (x86)\Inno Setup 6;%PATH%'

init:
  - ps: >-
      if($env:APPVEYOR_REPO_TAG -eq "true") {
        Update-AppveyorBuild -Version $env:APPVEYOR_REPO_TAG_NAME.Substring(1)
      }

install:
  - choco install -y innosetup

before_build:
  - curl -Sso "bin\WA2_en.exe" "https://cloud.disroot.org/s/MRQp6cw7DXCY3gr/download"

build_script:
  - ISCC.exe src\WA2.iss
  - ISCC.exe /DIS_DMM src\WA2.iss

artifacts:
  - path: out\WA2_patch.exe
    name: WA2 patch
  - path: out\WA2_patch_DMM.exe
    name: WA2 patch (DMM)

before_deploy:
  - ps: >-
      if(!$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED) {
        $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED = "* $env:APPVEYOR_REPO_COMMIT_MESSAGE"
      }

deploy:
  - provider: GitHub
    auth_token:
      secure: tZicH5QK+eVtmDDtBFAiIfKiTGo2hAhYUjYnANurws9QMQuDiXex05LiexEqGXUV
    artifact: out\WA2_patch.exe,out\WA2_patch_DMM.exe
    description: $(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
    prerelease: true
    on:
      APPVEYOR_REPO_TAG: true
